language: java

# Use container based infrastructure
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false
 
# Gradle caches
cache:
  directories:
    - $HOME/.gradle/wrapper
